# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0002_auto_20180403_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
