# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0004_auto_20180404_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposits',
            name='coin_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='withdrawalrequests',
            name='address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequests',
            name='coin_type',
            field=models.IntegerField(default=1),
        ),
    ]
