# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0005_auto_20180405_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposits',
            old_name='address',
            new_name='recipient_address',
        ),
        migrations.AddField(
            model_name='deposits',
            name='investment_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boots.InvestmentPlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposits',
            name='sender_address',
            field=models.TextField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
